# Generated by Django 4.2.13 on 2024-08-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='data',
            field=models.BinaryField(null=True),
        ),
    ]
